### ISSUE TITLE
Send Failed, Bootloop

### ISSUE THREAD

**Issue by wurst44** [kissste/ESP8266-Arduino-CC1101#1]
Hey, thanks for that example.
I could flash my ESP8266 (Node MCU) with your lib, but I am getting a bootloop and when trying the sending part that I found  it is also failing. 
I guess GDO0 is D1.
And I am not using GDO2? But I tried D2.

Any clues?

CC1101_PARTNUM 0 
CC1101_VERSION 20
CC1101_MARCSTATE 13
device initialized
CC1101_MARCSTATE 13
sent failed :(

..................

CC1101_PARTNUM 0
CC1101_VERSION 20 
CC1101_MARCSTATE 13
device initialized
CC1101_MARCSTATE 13
sent failed :(@� *¬Ô•�ñ*%D¦Ð†	Š‘"‚†2ÈÄÕPêŠ´�Qþ›þstart
CC1101_PARTNUM 0 
CC1101_VERSION 20
CC1101_MARCSTATE 13
device initialized
CC1101_MARCSTATE 13
sent failed :(@� *¬Ô•�ñ*%D¦Ð†	Š‘"‚†2ÈÄÕPêŠ´�Qþ›þstart 
CC1101_PARTNUM 0
CC1101_VERSION 20 
CC1101_MARCSTATE 13 
device initialized
CC1101_MARCSTATE 13
sent failed :(@� *¬Ô•�ñ*%D¦Ð†	Š‘"‚†2ÈÄÕPêŠ´�Qþ›þstart
CC1101_PARTNUM 0
CC1101_VERSION 20 
CC1101_MARCSTATE 13 

Thx

**Comment by kissste** [comment]
I'm not sure why are you having trouble running.

I'm using it here:
https://github.com/kissste/ESP8266-Powermon433

runs without any troubles

**Comment by wurst44** [comment]
Hi thank you!!
I am getting close to, I needed to set 
// pir
#define DPIN_PIR 6 -> to 4

So I am using ESP12-D1 for DPIN_OOK_RX and ESP12-D2 for DPIN_PIR 

#,Connected to XXX
#,IP address: 192.168.178.58
#,C110x init try
#,C110x init OK
0: 29; 1: 2E; 2: D; 3: 7; 4: D3; 5: 91; 6: 40; 7: 8; 8: 32; 9: 0; A: 0; B: 6; C: 0; D: 10; E: B0; F: 3F; 10: F6; 11: 43; 12: 37; 13: 0; 14: 0; 15: 40; 16: 7; 17: 3C; 18: 18; 19: 16; 1A: 6C; 1B: 43; 1C: 40; 1D: 91; 1E: 87; 1F: 6B; 20: FB; 21: 56; 22: 11; 23: E9; 24: 2A; 25: 0; 26: 1F; 27: 41; 28: 0; 29: 59; 2A: 59; 2B: 3F; 2C: 81; 2D: 35; 2E: 9; 2F: 0; 
30: 0; 31: 14; 32: 0; 33: 80; 34: 80; 35: 1; 36: 0; 37: 0; 38: 80; 39: 94; 3A: 0; 3B: 0; 3C: 0; 3D: 0; 3E: C6; 
#,Setup completed

Is there any need to set this?
//    setSyncWords(syncWords, sizeof(syncWords));
//    setTxPower(TransmitPower5dBm);
//    setFrequency(433.85);
//    setModemConfig(GFSK_Rb1_2Fd5_2);

I need to receive a the singnal from a 433 rc switch remote and than be able to send that saved value again.

Thanks/Greetz

**Comment by wurst44** [comment]
Hi I had success with fetching some values with these registers but I cannot find universal laws for the codes. Do I need to read other registers? Other wave configuration?

		uint8_t val1 = spiReadRegister(0x2B);
		uint8_t val2 = spiBurstReadRegister(0x34);
		uint8_t val3 = spiBurstReadRegister(0x38);

Thank you!
